parameters:
#    unica_innovare.example.class: Unica\InnovareBundle\Example

services:
#    unica_innovare.example:
#        class: %unica_innovare.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
