Unica\InnovareBundle\Entity\Anagrafica:
    type: entity
    table: anagrafica
    id:
        idAnagrafica:
            type: string
            nullable: false
            length: 11
            fixed: false
            comment: ''
            default: ''
            id: true
            column: id_anagrafica
            generator:
                strategy: IDENTITY
    fields:
        cognome:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
        nome:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
        email:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
        telefono1:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
        telefono2:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
        qualifica:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
